language: php
php:
  - 5.6
  - 5.5
  - 7.0
install:
  - travis_retry composer self-update && composer install
script:
  - vendor/bin/phpunit --testsuite "BorgerDk Article Export Service PHP SDK Unit Test Suite"
  - vendor/bin/phpcs --extensions=php --standard=PSR4 --report=summary -np src/ tests/