language: php

php:
  - 5.6
  - 5.5
  - 7.0

before_install:
  - travis_retry composer self-update && composer install

install:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --extensions=php --standard=PSR4 --report=summary -np src/ tests/